// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"go_online_course/internal/discount/delivery/http"
	"go_online_course/internal/discount/repository"
	"go_online_course/internal/discount/usecase"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeService(db *gorm.DB) *http.DiscountHandler {
	discountRepository := repository.NewDiscountRepository(db)
	discountUseCase := usecase.NewDiscountUseCase(discountRepository)
	discountHandler := http.NewDiscountHandler(discountUseCase)
	return discountHandler
}
