// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"go_online_course/internal/register/delivery/http"
	usecase2 "go_online_course/internal/register/usecase"
	"go_online_course/internal/user/repository"
	"go_online_course/internal/user/usecase"
	"go_online_course/pkg/mail/sendgrid"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializedService(db *gorm.DB) *http.RegisterHandler {
	userRepository := repository.NewUserRepositoryImpl(db)
	userUseCase := usecase.NewUserUseCase(userRepository)
	mail := sendgrid.NewMail()
	registerUseCase := usecase2.NewRegisterUseCase(userUseCase, mail)
	registerHandler := http.NewRegisterHandler(registerUseCase)
	return registerHandler
}
